name: "CD"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x deployment.sh && ./deployment.sh deploy-ops 7200 deploy test
