name: "CD"
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: echo "Starting deployment"
      - run: exec 3<>/dev/tcp/deploy-ops/7200 && echo "deploy test" 1>&3 && while IFS= read -r x <&3 ; [ "$x" != "EOF" ]; do echo "$x"; done ; exec 3<>-
      - run: echo "Deployment done"
