name: "CD"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - testing
          - staging
          - production
        description: Environment to deploy

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment }}
    runs-on: self-hosted
    outputs:
      status: ${{ steps.deployment.outputs.status }}
      release_name: ${{ steps.get_release_name.outputs.name }}
    steps:
      # xxd is required by deployment.sh to convert the PSK to hex
      - name: Install xxd
        run: apt-get update && apt-get install xxd

      - uses: actions/checkout@v2

      - name: Create PSK for deployment access
        run: echo "${{ secrets.DEPLOYMENT_PSK }}" > psk.key

      - name: Getting release name
        id: get_release_name
        run: |
          [ "${{ github.event.inputs.environment }}" = "testing" ] && playbook="dsp-test-01.yml"
          [ "${{ github.event.inputs.environment }}" = "staging" ] && playbook="dasch_stage.yml"
          [ "${{ github.event.inputs.environment }}" = "production" ] && playbook="dasch_prod.yml"
          release_name=$(cat "$playbook" | sed -n "s/^.*DSP_RELEASE:.*\"\(.*\)\".*$/\1/p")
          [ -z "$release_name" ] && { echo "Could not get release name"; exit 1; }
          echo "##[set-output name=name;]$release_name"

      - name: Run deployment
        id: deployment
        run: |
          chmod +x deployment.sh
          ./deployment.sh deploy-ops 7200 deploy ${{ github.event.inputs.environment }} ${{ secrets.GITHUB_TOKEN }}
          echo "##[set-output name=status;]$?"

  badges:
    needs: deploy
    if: ${{ always() }}
    runs-on: self-hosted
    steps:
      # Get environment name and status for badge
      - name: Get deployment status
        id: deployment_status
        run: |
          [ "${{ github.event.inputs.environment }}" = "testing" ] && echo "##[set-output name=label;]Testing"
          [ "${{ github.event.inputs.environment }}" = "staging" ] && echo "##[set-output name=label;]Staging"
          [ "${{ github.event.inputs.environment }}" = "production" ] && echo "##[set-output name=label;]Production"
          if [ "${{ needs.deploy.outputs.status }}" = "0" ]; then echo "##[set-output name=status;]${{ needs.deploy.outputs.release_name }} | OK"; else echo "##[set-output name=status;]${{ needs.deploy.outputs.release_name }} | Failure"; fi
          if [ "${{ needs.deploy.outputs.status }}" = "0" ]; then echo "##[set-output name=color;]green"; else echo "##[set-output name=color;]red"; fi

      # Everything below here is part of the badge action, slightly modified from
      # the example in https://github.com/emibcn/badge-action

      # Get current banch name to use it as dest directory
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Prepare environment
        id: environment
        run: |
          echo "##[set-output name=path;]${BADGE_PATH}"
          echo "##[set-output name=branch;]${BRANCH}"
        env:
          BADGE_PATH: ${{ steps.extract_branch.outputs.branch }}/${{ github.event.inputs.environment }}.svg
          BRANCH: badges

      # Checkout branch where the badge SVG will be saved
      - uses: actions/checkout@v1
        with:
          ref: ${{ steps.environment.outputs.branch }}

      # Create the directory where badges will be saved, if needed
      - name: Create destination directory
        env:
          BADGE_PATH: ${{ steps.environment.outputs.path }}
        run: mkdir -p "${BADGE_PATH%/*}"

      # Use the output from the `environment` step
      - name: Generate the badge SVG image
        uses: emibcn/badge-action@v1
        id: badge
        with:
          label: ${{ steps.deployment_status.outputs.label }}
          status: ${{ steps.deployment_status.outputs.status }}
          color: ${{ steps.deployment_status.outputs.color }}
          path: ${{ steps.environment.outputs.path }}

      # Commit and push badge SVG to the repository
      - name: Commit badge
        continue-on-error: true
        env:
          BADGE: ${{ steps.environment.outputs.path }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "${BADGE}"
          git commit -m "Add/Update badge"
      - name: Push badge commit
        uses: ad-m/github-push-action@v0.6.0
        if: ${{ success() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.environment.outputs.branch }}
